version: '2'
services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ".:/var/www/"
      - "~/.bash_history:/root/.bash_history"
    links:
      - "db"
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "1542"
      MYSQL_PASSWORD: "1542"
      MYSQL_DATABASE: "datacorp"